"""empty message

Revision ID: 295d19fe24cf
Revises: c08b0557d24f
Create Date: 2025-05-29 03:19:49.114254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295d19fe24cf'
down_revision = 'c08b0557d24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_planet')
    op.drop_table('favorite_character')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('character_id')

    op.create_table('favorite_character',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorite_character_character_id_fkey'),
    sa.ForeignKeyConstraint(['id'], ['favorite.id'], name='favorite_character_id_fkey1'),
    sa.PrimaryKeyConstraint('id', name='favorite_character_pkey')
    )
    op.create_table('favorite_planet',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['favorite.id'], name='favorite_planet_id_fkey1'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorite_planet_planet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_planet_pkey')
    )
    # ### end Alembic commands ###
